<a href="https://colab.research.google.com/github/enavid/ai-samurai-kata/blob/main/ztm_pytorch_kata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [13]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8924, 0.4468, 0.8770, 0.9768],
        [0.1666, 0.9065, 0.9159, 0.8289],
        [0.5503, 0.0431, 0.3122, 0.3814]])

In [14]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

In [21]:
# Create a range of tensors and tensors-like

one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [24]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [33]:
# Find out details about some tensor
some_tensor = torch.rand(3, 4)
some_tensor

some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [35]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0818, 0.9367, 0.5217, 0.0161],
        [0.0664, 0.1392, 0.3792, 0.2477],
        [0.0695, 0.3762, 0.3827, 0.4710]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x7c1f9214f8e0>
Device tensor is on: cpu
